### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by gagan-1998** [datastaxdevs/appdev-week3-graphql#531] opened 2021-09-22 22:34 UTC
Name: Gagan rohilla
Email: gaganrohilla1998@gmail.com
Linkedin Profile: https://www.linkedin.com/in/r0hillagagan/

App Hosted URL: https://awesome-neumann-843b25.netlify.app/

ATTACHED THE SCREENSHOT BELOW: 

GENRE: Bollywood
MOVIE NAME: Housefull, Singham

![Screenshot (133)](https://user-images.githubusercontent.com/59838795/134430745-30f09670-c01f-4d73-8279-b481a8ea3122.png)

**Comment by hemidactylus** [comment] 2021-09-23 12:13
Closing this since it's a duplicate of #532

**Closed by hemidactylus** 2021-09-23 12:13 UTC
Labels: homework, wait for review
