### ISSUE TITLE
[HW] Garv Anand

### ISSUE THREAD

**Issue by kritika11111** [datastaxdevs/appdev-week3-graphql#300] opened 2021-07-17 10:50 UTC
**Name:** Garv Anand![dd](https://user-images.githubusercontent.com/87203104/126034540-c8e1bc79-4de7-48ce-9323-bb95fed825c1.PNG)**Email:** garvanand03@gmail.com
**Linkedin Profile:** http://www.linkedin.com/in/garv-anand-476358217

Attach the homework screenshots below:
-----------------------------------------
<img width="884" alt="abc" src="https://user-images.githubusercontent.com/87203104/126034354-3f760cc0-4c59-4b44-80b8-961e8a0f664c.png">
<img width="884" alt="abc" src="https://user-images.githubusercontent.com/87203104/126034497-fd365443-c55f-463b-8b0c-c38da4c25c5f.png">
<img width="884" alt="abc" src="https://user-images.githubusercontent.com/87203104/126034565-9d338c4c-cae2-46bf-98d9-f9279c688383.PNG">
<img width="884" alt="abc" src="https://user-images.githubusercontent.com/87203104/126034553-9f4a5659-0fbd-4f98-8dc0-4fbd9881a2d9.PNG">

**Comment by kritika11111** [comment] 2021-07-17 16:41
![image](https://user-images.githubusercontent.com/87203104/126043709-0ff766fe-5f3a-4f45-865d-5634daecc2a0.png)
site is deployed

**Comment by SonicDMG** [comment] 2021-07-19 16:28
This is a duplicate of https://github.com/datastaxdevs/appdev-week3-graphql/issues/301 and 301 has the correct name and email. Closing this issue and using the other.

**Closed** 2021-07-19 16:29 UTC
Labels: duplicate, homework
