### ISSUE TITLE
[HW] Garv Anand

### ISSUE THREAD

**Issue by kritika11111** [datastaxdevs/appdev-week3-graphql#301] opened 2021-07-18 18:05 UTC
**Name:** Garv Anand
**Email:** garvanand03@gmail.com
**Linkedin Profile:** http://www.linkedin.com/in/garv-anand-476358217

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/87203104/126077654-729c9e34-70c8-4422-9d8e-5c731e72fc88.png)
![image](https://user-images.githubusercontent.com/87203104/126077668-7deb0a96-2c34-4e7c-a65a-76930e5ad75d.png)
![image](https://user-images.githubusercontent.com/87203104/126077688-9d6f0b39-86cf-4f11-9920-1357c074d12f.png)
![image](https://user-images.githubusercontent.com/87203104/126077704-c5d01ba3-5b9d-4669-b14a-bec403a9e82d.png)
![image](https://user-images.githubusercontent.com/87203104/126077728-f7999280-151d-4d89-9c6a-4fbc3be3758d.png)
![image](https://user-images.githubusercontent.com/87203104/126077737-d078fb37-15b5-444c-b452-5ff0adfe949f.png)

**Comment by SonicDMG** [comment] 2021-07-19 16:28
This looks like a duplicate of https://github.com/datastaxdevs/appdev-week3-graphql/issues/300. Closing this issue.

**Comment by HadesArchitect** [comment] 2021-07-19 16:29
Hey **Garv Anand**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/klpm1eIYTRKoYGzI3KUKjA

**Closed** 2021-07-24 16:20 UTC
Labels: accepted, badge issued, homework
